# Generated by Django 4.1.7 on 2024-02-14 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sponsor', models.ImageField(upload_to='team/')),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
                'ordering': ['-updated_at'],
            },
        ),
    ]
