# Generated by Django 4.1.7 on 2024-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='sponsor/'),
        ),
    ]
