# Generated by Django 4.1.7 on 2024-02-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_otherprogramimages_otherprojectimages_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherprojectimages',
            name='project',
        ),
        migrations.DeleteModel(
            name='OtherProgramImages',
        ),
        migrations.DeleteModel(
            name='OtherProjectImages',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
