# Generated by Django 4.1.7 on 2024-02-15 07:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_bellore_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bellore_settings',
            name='main_logo',
            field=django_resized.forms.ResizedImageField(crop=None, default='10', force_format=None, keep_meta=True, quality=90, scale=None, size=[1920, 1080], upload_to='logo/'),
        ),
    ]
