# Generated by Django 4.1.7 on 2024-02-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_settings_delete_bellore_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['updated_at'], 'verbose_name_plural': 'Teams'},
        ),
    ]
