# Generated by Django 4.1.7 on 2024-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_team_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
