# Generated by Django 4.1.7 on 2024-03-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_sponsor_description_sponsor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
