# Generated by Django 4.1.7 on 2024-03-19 06:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_settings_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='objectives',
            field=ckeditor.fields.RichTextField(default='1'),
        ),
    ]
