# Generated by Django 4.1.7 on 2024-03-19 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_settings_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='objectives',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
