# Generated by Django 4.1.7 on 2024-02-14 19:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('blog_description', ckeditor.fields.RichTextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='blogcover')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('read_count', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('publish_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('is_censored', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
