# Generated by Django 4.1.7 on 2024-02-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_date',
        ),
    ]
