# Generated by Django 4.1.7 on 2024-02-14 12:35

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=90, scale=None, size=[1920, 1080], upload_to='program/')),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('in_progress', models.BooleanField(blank=True, default=False, null=True)),
                ('youtube_link', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Programs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherProgramImages',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('other_program_images', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[1920, 1080], upload_to='program/')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
            options={
                'verbose_name_plural': 'Other program images',
            },
        ),
    ]
