# Generated by Django 4.1.7 on 2024-02-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='in_progress',
        ),
        migrations.AddField(
            model_name='program',
            name='flickr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
